[project]
name = "manage-tasks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "VityaZlat", email = "viktor-gololobov@yandex.ru" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
manage-tasks = "manage_tasks:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
